<a href="https://colab.research.google.com/github/syejin2004/deep-learning/blob/main/inclass/deep_learning_0313.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 딥러닝 프로그래밍 실습

### 일차원 배열

In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32, shape=[3])
b = tf.Variable(3)
c = tf.add(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(c, {a: [1, 2, 3]}))

[4 5 6]


### 다차원 배열

In [13]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c = tf.multiply(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(c, {a: [[1, 2, 3], [1, 2, 3]], b: [[5, 2, 3], [1, 2, 3]]}))

[[5 4 9]
 [1 4 9]]


In [28]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c = tf.add(a, b)
d = tf.subtract(a, b)
e = tf.multiply(a,b)
f = tf.mod(a, b)


init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print('Plus =>', sess.run(c, {a: [[1, 2, 3], [1, 2, 3]], b: [[5, 2, 3], [1, 2, 3]]}))
  print('Mnius =>',sess.run(d, {a: [[1, 2, 3], [1, 2, 3]], b: [[5, 2, 3], [1, 2, 3]]}))
  print('Mutiply =>',sess.run(e, {a: [[1, 2, 3], [1, 2, 3]], b: [[5, 2, 3], [1, 2, 3]]}))
  print('Div =>',sess.run(f, {a: [[1, 2, 3], [1, 2, 3]], b: [[5, 2, 3], [1, 2, 3]]}))

Plus => [[6 4 6]
 [2 4 6]]
Mnius => [[-4  0  0]
 [ 0  0  0]]
Mutiply => [[5 4 9]
 [1 4 9]]
Div => [[1 0 0]
 [0 0 0]]
